spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: false

booking:
  service:
    external-host: booking-service
    external-port: 9090

grpc:
  client:
    booking-service:
      address: ${BOOKING_SERVICE_EXTERNAL_HOST:booking-service}:${BOOKING_SERVICE_EXTERNAL_PORT:9090}
      negotiation-type: plaintext
      enable-keep-alive: true

