version: '3.8'

services:
  monolith:
    build:
      context: ../../hotelio-monolith
      dockerfile: Dockerfile
    container_name: hotelio-monolith
    ports:
      - "8084:8080"
    networks:
      - hotelio-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://monolith-db:5432/hotelio
      SPRING_DATASOURCE_USERNAME: hotelio
      SPRING_DATASOURCE_PASSWORD: hotelio
      BOOKING_SERVICE_EXTERNAL_HOST: booking-service
      BOOKING_SERVICE_EXTERNAL_PORT: 9090

  monolith-db:
    image: postgres:15
    container_name: hotelio-db
    environment:
      POSTGRES_USER: hotelio
      POSTGRES_PASSWORD: hotelio
      POSTGRES_DB: hotelio
    ports:
      - "5432:5432"
    volumes:
      - monolith-db-data:/var/lib/postgresql/data
    networks:
      - hotelio-net

  booking-service:
    build:
      context: ../../../../microservices/booking-service
      dockerfile: Dockerfile
    container_name: booking-service
    ports:
      - "9090:9090"
    networks:
      - hotelio-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://booking-service-db:5432/booking
      SPRING_DATASOURCE_USERNAME: booking
      SPRING_DATASOURCE_PASSWORD: booking
      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:9092

  booking-service-db:
    image: postgres:15
    container_name: booking-service-db
    environment:
      POSTGRES_USER: booking
      POSTGRES_PASSWORD: booking
      POSTGRES_DB: booking
    ports:
      - "5433:5432"
    volumes:
      - booking-service-db-data:/var/lib/postgresql/data
    networks:
      - hotelio-net

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - hotelio-net
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - hotelio-net

  apollo-gateway:
    build: ./gateway
    ports:
      - "4000:4000"
    depends_on:
      - booking-subgraph
      - hotel-subgraph
      - promocode-subgraph
    networks:
      - hotelio-net
    environment:
      - BOOKING_SUBGRAPH_URL=http://booking-subgraph:4001
      - HOTEL_SUBGRAPH_URL=http://hotel-subgraph:4002
      - PROMOCODE_SUBGRAPH_URL=http://promocode-subgraph:4003

  booking-subgraph:
    build: ./booking-subgraph
    ports:
      - "4001:4001"
    environment:
      - USE_MOCKS=true
      - MONOLITH_URL=http://monolith:8080
    networks:
      - hotelio-net

  hotel-subgraph:
    build: ./hotel-subgraph
    ports:
      - "4002:4002"
    networks:
      - hotelio-net
    environment:
      - MONOLITH_URL=http://monolith:8080

  promocode-subgraph:
    build: ./promocode-subgraph
    ports:
      - "4003:4003"
    networks:
      - hotelio-net
    environment:
      - MONOLITH_URL=http://monolith:8080

volumes:
  monolith-db-data:
  booking-service-db-data:
  booking-history-db-data:


networks:
  hotelio-net:
    external: true